# borrowed from https://github.com/goreleaser/homebrew-tap
language: minimal
if: branch = master
before_install:
  - curl -L https://git.io/get_helm.sh | bash
  - helm init --client-only
script:
  - helm repo index . --url https://ninjaneers-team.github.io/charts/
